installation avec package

diff --git a/install_sct b/install_sct
--- a/install_sct
+++ b/install_sct
@@ -125,27 +125,36 @@ usage() {
 echo -e "\nWelcome to the SCT installer!"
 
 
-while getopts ":dmh" opt; do
-  case $opt in
-    d)
-      echo " data directory will not be (re)-installed"
-      NO_DATA_INSTALL=yes
-      ;;
-    m)
-      echo " miniconda python will not be (re)-installed "
-      NO_CONDA_INSTALL=yes
-      ;;
-    h)
-      usage
-      exit 0
-      ;;
-    \?)
-      usage
-      exit 1
-      ;;
-  esac
-done
+# Get installation type (from git or from package)
+if [ -d ".git" ]; then
+  # folder .git exist, therefore it is a git installation
+  INSTALL_TYPE="git"
+else
+  INSTALL_TYPE="package"
+fi
 
+if [[ ${INSTALL_TYPE} == git ]]; then
+  while getopts ":dmh" opt; do
+    case $opt in
+      d)
+        echo " data directory will not be (re)-installed"
+        NO_DATA_INSTALL=yes
+        ;;
+      m)
+        echo " miniconda python will not be (re)-installed "
+        NO_CONDA_INSTALL=yes
+        ;;
+      h)
+        usage
+        exit 0
+        ;;
+      \?)
+        usage
+        exit 1
+        ;;
+    esac
+  done
+fi
 
 if [ -e "version.txt" ]; then
   SCT_VERSION=`cat version.txt`
@@ -153,14 +162,6 @@ else
   echo "ERROR: version.txt not found."
   echo "The install_sct script must be execute from the source directory"
   exit 1
-fi
-
-# Get installation type (from git or from package)
-if [ -d ".git" ]; then
-  # folder .git exist, therefore it is a git installation
-  INSTALL_TYPE="git"
-else
-  INSTALL_TYPE="package"
 fi
 
 # Fetch OS type
@@ -194,7 +195,7 @@ THE_CSHRC=${HOME}/.cshrc
 if [[ $INSTALL_TYPE == "git" ]]; then
   INSTALL_DIR=$SCT_SOURCE
 else
-  INSTALL_DIR="${HOME}sct_${SCT_VERSION}"
+  INSTALL_DIR="${HOME}/sct_${SCT_VERSION}"
 fi
 
 # Set install dir
@@ -205,8 +206,13 @@ while  true ; do
     read change_default_path
   done
   if [[ ${change_default_path} =~ ^[Yy] ]]; then
-    # user accepts default path --> exit loop
-    break
+      # user accepts default path --> exit loop
+
+      # In the package intalation the default tipically does not exist
+      # fails quietly if INSTALL_DIR already exist
+      mkdir ${INSTALL_DIR}  2>/dev/null
+
+      break
   fi
   echo -n "Choose install directory. Warning! Give full path (e.g. /usr/django/sct_v3.0): "
   # user enters new path
@@ -242,24 +248,27 @@ while  true ; do
     INSTALL_DIR=${new_install}
     break
   fi
+
 done
 
 SCT_DIR=${INSTALL_DIR}
 
 # Clean old install setup in bin/
 echo "Removing sct and isct softlink from ${SCT_DIR}/${BIN_DIR}"
-find ${SCT_DIR}/${BIN_DIR} -type l -name "sct_*" -exec rm {} \;
-find ${SCT_DIR}/${BIN_DIR} -type l -name "isct_*" -exec rm {} \;
-
+find ${SCT_DIR}/${BIN_DIR} -type l -name "sct_*" -exec rm {} \; 2>/dev/null
+find ${SCT_DIR}/${BIN_DIR} -type l -name "isct_*" -exec rm {} \; 2>/dev/null
 
 # Copy files to destination directory
-if [ "${SCT_DIR}" != "${SCT_SOURCE}" ]; then
+if [ "${SCT_DIR}" != "${SCT_SOURCE}" -a "${INSTALL_TYPE}" == "git" ]; then
   echo -e "\nCopying source files from ${SCT_SOURCE} to ${SCT_DIR}"
   cp -vR ${SCT_SOURCE}/${SCRIPT_DIR}  ${SCT_DIR}/.
   cp ${SCT_SOURCE}/version.txt  ${SCT_DIR}/.
   mkdir -p ${SCT_DIR}/install
   cp -vRp ${SCT_SOURCE}/install ${SCT_DIR}
   cp -vRp ${SCT_SOURCE}/testing ${SCT_DIR}/.
+elif [ "${SCT_DIR}" != "${SCT_SOURCE}" -a "${INSTALL_TYPE}" == "package" ]; then
+  echo moving sct source to ${SCT_DIR}
+  cp -Rp ${SCT_SOURCE}/* ${SCT_DIR}/.
 else
   echo -e "\nSkipping copy of source files (source and destination folders are the same)"
 fi
@@ -273,70 +282,70 @@ if [ ! -f "version.txt" ]; then
   exit 1
 fi
 
-
-# Create launchers for Python scripts
-echo -e "\nCreate launchers for Python scripts"
-cmd="mkdir -p ${SCT_DIR}/${BIN_DIR}"; echo ">> "$cmd; $cmd
-# update_bin has to be executed from the install directory
-cmd="cd ${SCT_DIR}/install"; echo ">> "$cmd; $cmd
-cmd="./update_bin.sh"; echo ">> "$cmd; $cmd  # N.B. This script needs to be run from /install folder (because uses relative path)
-# Copy binaries
-echo -e "\nInstalling binaries..."
-download  ${TMP_DIR}/sct_binaries.tar.gz https://dl.dropboxusercontent.com/u/20592661/sct/bin/${OS}/sct_binaries.tar.gz
-# unzip binaries
-ls ${TMP_DIR} > /dev/null
-cmd="tar -C ${SCT_DIR}/${BIN_DIR} -zxvf ${TMP_DIR}/sct_binaries.tar.gz"; echo ">> "$cmd; $cmd
-
-
-
-if [ ${NO_DATA_INSTALL} ]; then
-  echo "data/ will not vbe (re)-install"
-else
-  cmd="rm -rf ${SCT_DIR}/${DATA_DIR}"; echo ">> "$cmd; $cmd
-  # Download data
-  echo -e "\nInstalling data..."
-  cmd="mkdir -p ${SCT_DIR}/${DATA_DIR}"; echo ">> "$cmd; $cmd
-  download  ${TMP_DIR}/${DATA_DIR}.tar.gz https://dl.dropboxusercontent.com/u/20592661/sct/MNI-Poly-AMU.tar.gz
+if [[ ${INSTALL_TYPE} == git ]]; then
+  # Create launchers for Python scripts
+  echo -e "\nCreate launchers for Python scripts"
+  cmd="mkdir -p ${SCT_DIR}/${BIN_DIR}"; echo ">> "$cmd; $cmd
+  # update_bin has to be executed from the install directory
+  cmd="cd ${SCT_DIR}/install"; echo ">> "$cmd; $cmd
+  cmd="./update_bin.sh"; echo ">> "$cmd; $cmd  # N.B. This script needs to be run from /install folder (because uses relative path)
+  # Copy binaries
+  echo -e "\nInstalling binaries..."
+  download  ${TMP_DIR}/sct_binaries.tar.gz https://dl.dropboxusercontent.com/u/20592661/sct/bin/${OS}/sct_binaries.tar.gz
   # unzip binaries
-  cmd="tar -C ${SCT_DIR} -zxvf ${TMP_DIR}/data.tar.gz"; echo ">> "$cmd; $cmd
+  ls ${TMP_DIR} > /dev/null
+  cmd="tar -C ${SCT_DIR}/${BIN_DIR} -zxvf ${TMP_DIR}/sct_binaries.tar.gz"; echo ">> "$cmd; $cmd
+
+
+
+  if [ ${NO_DATA_INSTALL} ]; then
+    echo "data/ will not vbe (re)-install"
+  else
+    cmd="rm -rf ${SCT_DIR}/${DATA_DIR}"; echo ">> "$cmd; $cmd
+    # Download data
+    echo -e "\nInstalling data..."
+    cmd="mkdir -p ${SCT_DIR}/${DATA_DIR}"; echo ">> "$cmd; $cmd
+    download  ${TMP_DIR}/${DATA_DIR}.tar.gz https://dl.dropboxusercontent.com/u/20592661/sct/MNI-Poly-AMU.tar.gz
+    # unzip binaries
+    cmd="tar -C ${SCT_DIR} -zxvf ${TMP_DIR}/data.tar.gz"; echo ">> "$cmd; $cmd
+  fi
+
+  if [ ${NO_CONDA_INSTALL} ]; then
+    echo "python/ will not vbe (re)-install"
+  else
+    cmd="rm -rf ${SCT_DIR}/${PYTHON_DIR}"; echo ">> "$cmd; $cmd
+    # Install Python conda
+    echo -e "\nInstalling conda..."
+    cmd="mkdir ${SCT_DIR}/${PYTHON_DIR}"; echo ">> "$cmd; $cmd
+    # downloading
+    download  ${TMP_DIR}/miniconda.sh https://dl.dropboxusercontent.com/u/20592661/sct/miniconda/${OS}/miniconda.sh
+    # run conda installer
+    cmd="bash ${TMP_DIR}/miniconda.sh -p ${SCT_DIR}/${PYTHON_DIR} -b -f"; echo ">> "$cmd; $cmd
+
+    # activate miniconda
+    cmd=". ${SCT_DIR}/${PYTHON_DIR}/bin/activate ${SCT_DIR}/${PYTHON_DIR}"; echo ">> "$cmd; $cmd
+
+
+    # Install Python dependencies
+    echo -e "\nInstalling Python dependencies..."
+    # N.B. the flag --ignore-installed is required because if user already
+    # has other dependencies, it will not install
+    conda install --yes --file ${SCT_SOURCE}/install/requirements/requirementsConda.txt
+    pip install --ignore-installed  -r ${SCT_SOURCE}/install/requirements/requirementsPip.txt
+
+    # Install wheels
+    echo -e "\nInstalling external Python dependencies..."
+    download  ${TMP_DIR}/wheels.tar.gz https://dl.dropboxusercontent.com/u/20592661/sct/wheel/${OS}/wheels.tar.gz
+    tar -C ${TMP_DIR} -zxvf ${TMP_DIR}/wheels.tar.gz
+    # get file names
+    dipy_whl=`ls ${TMP_DIR}/dipy*.whl`
+    ornlm_whl=`ls ${TMP_DIR}/ornlm*.whl`
+    pip install --ignore-installed ${dipy_whl} ${ornlm_whl}
+
+  fi
+
+  echo -e "All requirement installed!"
 fi
-
-if [ ${NO_CONDA_INSTALL} ]; then
-  echo "python/ will not vbe (re)-install"
-else
-  cmd="rm -rf ${SCT_DIR}/${PYTHON_DIR}"; echo ">> "$cmd; $cmd
-  # Install Python conda
-  echo -e "\nInstalling conda..."
-  cmd="mkdir ${SCT_DIR}/${PYTHON_DIR}"; echo ">> "$cmd; $cmd
-  # downloading
-  download  ${TMP_DIR}/miniconda.sh https://dl.dropboxusercontent.com/u/20592661/sct/miniconda/${OS}/miniconda.sh
-  # run conda installer
-  cmd="bash ${TMP_DIR}/miniconda.sh -p ${SCT_DIR}/${PYTHON_DIR} -b -f"; echo ">> "$cmd; $cmd
-
-  # activate miniconda
-  cmd=". ${SCT_DIR}/${PYTHON_DIR}/bin/activate ${SCT_DIR}/${PYTHON_DIR}"; echo ">> "$cmd; $cmd
-
-
-  # Install Python dependencies
-  echo -e "\nInstalling Python dependencies..."
-  # N.B. the flag --ignore-installed is required because if user already
-  # has other dependencies, it will not install
-  conda install --yes --file ${SCT_SOURCE}/install/requirements/requirementsConda.txt
-  pip install --ignore-installed  -r ${SCT_SOURCE}/install/requirements/requirementsPip.txt
-
-  # Install wheels
-  echo -e "\nInstalling external Python dependencies..."
-  download  ${TMP_DIR}/wheels.tar.gz https://dl.dropboxusercontent.com/u/20592661/sct/wheel/${OS}/wheels.tar.gz
-  tar -C ${TMP_DIR} -zxvf ${TMP_DIR}/wheels.tar.gz
-  # get file names
-  dipy_whl=`ls ${TMP_DIR}/dipy*.whl`
-  ornlm_whl=`ls ${TMP_DIR}/ornlm*.whl`
-  pip install --ignore-installed ${dipy_whl} ${ornlm_whl}
-
-fi
-
-echo -e "All requirement installed!"
-
 # update PATH environment
 if [[ $UID != 0 ]]; then
   while  [[ ! ${add_to_path} =~ ^([Yy](es)?|[Nn]o?)$ ]] ; do
@@ -359,7 +368,7 @@ if [[ $UID != 0 ]]; then
 fi
 
 # Make sure sct scripts are executable
-find ${SCT_DIR}/${BIN_DIR}/ -maxdepth 2 -type f -exec chmod 755 {} \;
+find ${SCT_DIR}/${BIN_DIR} -maxdepth 1 -type f -exec chmod 755 {} \;
 
 # Run check dependencies
 echo -e "\nRun sct_check_dependencies..."
